apiVersion: v1
kind: ServiceAccount
metadata:
  name: akil-collector
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: akil-collector
    app.kubernetes.io/part-of: akil
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: akil-aggregator
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: akil-aggregator
    app.kubernetes.io/part-of: akil
