---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: akil-aggregator-sa
  namespace: akil-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akil-aggregator-role
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akil-aggregator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: akil-aggregator-role
subjects:
- kind: ServiceAccount
  name: akil-aggregator-sa
  namespace: akil-system
