apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: akil-scheduler
    plugins:
      score:
        enabled:
          - name: AkilScore
            weight: 25
    pluginConfig:
      - name: AkilScore
        args:
          aggregatorAddress: "akil-aggregator.akil-system.svc.cluster.local:50051"
