// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.5
// source: pkg/proto/akil.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED     EventType = 0
	EventType_EVENT_TYPE_PAGE_FAULT      EventType = 1
	EventType_EVENT_TYPE_CACHE_MISS      EventType = 2
	EventType_EVENT_TYPE_LOCK_CONTENTION EventType = 3
	EventType_EVENT_TYPE_CONTEXT_SWITCH  EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_PAGE_FAULT",
		2: "EVENT_TYPE_CACHE_MISS",
		3: "EVENT_TYPE_LOCK_CONTENTION",
		4: "EVENT_TYPE_CONTEXT_SWITCH",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":     0,
		"EVENT_TYPE_PAGE_FAULT":      1,
		"EVENT_TYPE_CACHE_MISS":      2,
		"EVENT_TYPE_LOCK_CONTENTION": 3,
		"EVENT_TYPE_CONTEXT_SWITCH":  4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_akil_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_pkg_proto_akil_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{0}
}

type ProfileConfidence int32

const (
	ProfileConfidence_PROFILE_CONFIDENCE_UNKNOWN ProfileConfidence = 0
	ProfileConfidence_PROFILE_CONFIDENCE_LOW     ProfileConfidence = 1 // < 100 samples in window
	ProfileConfidence_PROFILE_CONFIDENCE_MEDIUM  ProfileConfidence = 2 // 100–1000 samples
	ProfileConfidence_PROFILE_CONFIDENCE_HIGH    ProfileConfidence = 3 // > 1000 samples
)

// Enum value maps for ProfileConfidence.
var (
	ProfileConfidence_name = map[int32]string{
		0: "PROFILE_CONFIDENCE_UNKNOWN",
		1: "PROFILE_CONFIDENCE_LOW",
		2: "PROFILE_CONFIDENCE_MEDIUM",
		3: "PROFILE_CONFIDENCE_HIGH",
	}
	ProfileConfidence_value = map[string]int32{
		"PROFILE_CONFIDENCE_UNKNOWN": 0,
		"PROFILE_CONFIDENCE_LOW":     1,
		"PROFILE_CONFIDENCE_MEDIUM":  2,
		"PROFILE_CONFIDENCE_HIGH":    3,
	}
)

func (x ProfileConfidence) Enum() *ProfileConfidence {
	p := new(ProfileConfidence)
	*p = x
	return p
}

func (x ProfileConfidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileConfidence) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_akil_proto_enumTypes[1].Descriptor()
}

func (ProfileConfidence) Type() protoreflect.EnumType {
	return &file_pkg_proto_akil_proto_enumTypes[1]
}

func (x ProfileConfidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileConfidence.Descriptor instead.
func (ProfileConfidence) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{1}
}

type TelemetryBatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeName         string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	BatchTimestampNs int64                  `protobuf:"varint,2,opt,name=batch_timestamp_ns,json=batchTimestampNs,proto3" json:"batch_timestamp_ns,omitempty"`
	Events           []*TelemetryEvent      `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_pkg_proto_akil_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_akil_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryBatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TelemetryBatch) GetBatchTimestampNs() int64 {
	if x != nil {
		return x.BatchTimestampNs
	}
	return 0
}

func (x *TelemetryBatch) GetEvents() []*TelemetryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TelemetryEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EventType   EventType              `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=akil.v1.EventType" json:"event_type,omitempty"`
	WorkloadKey string                 `protobuf:"bytes,2,opt,name=workload_key,json=workloadKey,proto3" json:"workload_key,omitempty"` // "namespace/Kind/name"
	TimestampNs int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TelemetryEvent_PageFault
	//	*TelemetryEvent_CacheMiss
	//	*TelemetryEvent_LockContention
	//	*TelemetryEvent_CtxSwitch
	Payload       isTelemetryEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_pkg_proto_akil_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_akil_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *TelemetryEvent) GetWorkloadKey() string {
	if x != nil {
		return x.WorkloadKey
	}
	return ""
}

func (x *TelemetryEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *TelemetryEvent) GetPayload() isTelemetryEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TelemetryEvent) GetPageFault() *PageFaultEvent {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryEvent_PageFault); ok {
			return x.PageFault
		}
	}
	return nil
}

func (x *TelemetryEvent) GetCacheMiss() *CacheMissEvent {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryEvent_CacheMiss); ok {
			return x.CacheMiss
		}
	}
	return nil
}

func (x *TelemetryEvent) GetLockContention() *LockContentionEvent {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryEvent_LockContention); ok {
			return x.LockContention
		}
	}
	return nil
}

func (x *TelemetryEvent) GetCtxSwitch() *ContextSwitchEvent {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryEvent_CtxSwitch); ok {
			return x.CtxSwitch
		}
	}
	return nil
}

type isTelemetryEvent_Payload interface {
	isTelemetryEvent_Payload()
}

type TelemetryEvent_PageFault struct {
	PageFault *PageFaultEvent `protobuf:"bytes,4,opt,name=page_fault,json=pageFault,proto3,oneof"`
}

type TelemetryEvent_CacheMiss struct {
	CacheMiss *CacheMissEvent `protobuf:"bytes,5,opt,name=cache_miss,json=cacheMiss,proto3,oneof"`
}

type TelemetryEvent_LockContention struct {
	LockContention *LockContentionEvent `protobuf:"bytes,6,opt,name=lock_contention,json=lockContention,proto3,oneof"`
}

type TelemetryEvent_CtxSwitch struct {
	CtxSwitch *ContextSwitchEvent `protobuf:"bytes,7,opt,name=ctx_switch,json=ctxSwitch,proto3,oneof"`
}

func (*TelemetryEvent_PageFault) isTelemetryEvent_Payload() {}

func (*TelemetryEvent_CacheMiss) isTelemetryEvent_Payload() {}

func (*TelemetryEvent_LockContention) isTelemetryEvent_Payload() {}

func (*TelemetryEvent_CtxSwitch) isTelemetryEvent_Payload() {}

type PageFaultEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMajor       bool                   `protobuf:"varint,1,opt,name=is_major,json=isMajor,proto3" json:"is_major,omitempty"` // true = major (disk I/O), false = minor
	Address       uint64                 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageFaultEvent) Reset() {
	*x = PageFaultEvent{}
	mi := &file_pkg_proto_akil_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageFaultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageFaultEvent) ProtoMessage() {}

func (x *PageFaultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_akil_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageFaultEvent.ProtoReflect.Descriptor instead.
func (*PageFaultEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{2}
}

func (x *PageFaultEvent) GetIsMajor() bool {
	if x != nil {
		return x.IsMajor
	}
	return false
}

func (x *PageFaultEvent) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

type CacheMissEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MissCountDelta uint64                 `protobuf:"varint,1,opt,name=miss_count_delta,json=missCountDelta,proto3" json:"miss_count_delta,omitempty"` // number of misses since last sample
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CacheMissEvent) Reset() {
	*x = CacheMissEvent{}
	mi := &file_pkg_proto_akil_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheMissEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheMissEvent) ProtoMessage() {}

func (x *CacheMissEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_akil_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheMissEvent.ProtoReflect.Descriptor instead.
func (*CacheMissEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{3}
}

func (x *CacheMissEvent) GetMissCountDelta() uint64 {
	if x != nil {
		return x.MissCountDelta
	}
	return 0
}

type LockContentionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockAddress   uint64                 `protobuf:"varint,1,opt,name=lock_address,json=lockAddress,proto3" json:"lock_address,omitempty"`
	DurationNs    int64                  `protobuf:"varint,2,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"` // time spent waiting on the lock
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockContentionEvent) Reset() {
	*x = LockContentionEvent{}
	mi := &file_pkg_proto_akil_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockContentionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockContentionEvent) ProtoMessage() {}

func (x *LockContentionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_akil_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockContentionEvent.ProtoReflect.Descriptor instead.
func (*LockContentionEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{4}
}

func (x *LockContentionEvent) GetLockAddress() uint64 {
	if x != nil {
		return x.LockAddress
	}
	return 0
}

func (x *LockContentionEvent) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

type ContextSwitchEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrevWorkloadKey string                 `protobuf:"bytes,1,opt,name=prev_workload_key,json=prevWorkloadKey,proto3" json:"prev_workload_key,omitempty"` // workload that was switched out
	PrevState       int32                  `protobuf:"varint,2,opt,name=prev_state,json=prevState,proto3" json:"prev_state,omitempty"`                    // task state of the outgoing process
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContextSwitchEvent) Reset() {
	*x = ContextSwitchEvent{}
	mi := &file_pkg_proto_akil_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextSwitchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextSwitchEvent) ProtoMessage() {}

func (x *ContextSwitchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_akil_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextSwitchEvent.ProtoReflect.Descriptor instead.
func (*ContextSwitchEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{5}
}

func (x *ContextSwitchEvent) GetPrevWorkloadKey() string {
	if x != nil {
		return x.PrevWorkloadKey
	}
	return ""
}

func (x *ContextSwitchEvent) GetPrevState() int32 {
	if x != nil {
		return x.PrevState
	}
	return 0
}

type IngestAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AckedTimestampNs  int64                  `protobuf:"varint,1,opt,name=acked_timestamp_ns,json=ackedTimestampNs,proto3" json:"acked_timestamp_ns,omitempty"`
	ApplyBackpressure bool                   `protobuf:"varint,2,opt,name=apply_backpressure,json=applyBackpressure,proto3" json:"apply_backpressure,omitempty"` // if true, collector should slow down
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_pkg_proto_akil_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_akil_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{6}
}

func (x *IngestAck) GetAckedTimestampNs() int64 {
	if x != nil {
		return x.AckedTimestampNs
	}
	return 0
}

func (x *IngestAck) GetApplyBackpressure() bool {
	if x != nil {
		return x.ApplyBackpressure
	}
	return false
}

type ProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadKey   string                 `protobuf:"bytes,1,opt,name=workload_key,json=workloadKey,proto3" json:"workload_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileRequest) Reset() {
	*x = ProfileRequest{}
	mi := &file_pkg_proto_akil_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRequest) ProtoMessage() {}

func (x *ProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_akil_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRequest.ProtoReflect.Descriptor instead.
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{7}
}

func (x *ProfileRequest) GetWorkloadKey() string {
	if x != nil {
		return x.WorkloadKey
	}
	return ""
}

type RuntimeProfile struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WorkloadKey         string                 `protobuf:"bytes,1,opt,name=workload_key,json=workloadKey,proto3" json:"workload_key,omitempty"`
	PageFaultRate       float64                `protobuf:"fixed64,2,opt,name=page_fault_rate,json=pageFaultRate,proto3" json:"page_fault_rate,omitempty"`                   // faults/sec (sliding window average)
	CacheMissRate       float64                `protobuf:"fixed64,3,opt,name=cache_miss_rate,json=cacheMissRate,proto3" json:"cache_miss_rate,omitempty"`                   // misses/sec
	LockContentionRatio float64                `protobuf:"fixed64,4,opt,name=lock_contention_ratio,json=lockContentionRatio,proto3" json:"lock_contention_ratio,omitempty"` // fraction of time in contention [0.0, 1.0]
	ContextSwitchRate   float64                `protobuf:"fixed64,5,opt,name=context_switch_rate,json=contextSwitchRate,proto3" json:"context_switch_rate,omitempty"`       // switches/sec
	SampleCount         int64                  `protobuf:"varint,6,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`                            // total events in current window
	WindowStartNs       int64                  `protobuf:"varint,7,opt,name=window_start_ns,json=windowStartNs,proto3" json:"window_start_ns,omitempty"`
	WindowEndNs         int64                  `protobuf:"varint,8,opt,name=window_end_ns,json=windowEndNs,proto3" json:"window_end_ns,omitempty"`
	Confidence          ProfileConfidence      `protobuf:"varint,9,opt,name=confidence,proto3,enum=akil.v1.ProfileConfidence" json:"confidence,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RuntimeProfile) Reset() {
	*x = RuntimeProfile{}
	mi := &file_pkg_proto_akil_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeProfile) ProtoMessage() {}

func (x *RuntimeProfile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_akil_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeProfile.ProtoReflect.Descriptor instead.
func (*RuntimeProfile) Descriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimeProfile) GetWorkloadKey() string {
	if x != nil {
		return x.WorkloadKey
	}
	return ""
}

func (x *RuntimeProfile) GetPageFaultRate() float64 {
	if x != nil {
		return x.PageFaultRate
	}
	return 0
}

func (x *RuntimeProfile) GetCacheMissRate() float64 {
	if x != nil {
		return x.CacheMissRate
	}
	return 0
}

func (x *RuntimeProfile) GetLockContentionRatio() float64 {
	if x != nil {
		return x.LockContentionRatio
	}
	return 0
}

func (x *RuntimeProfile) GetContextSwitchRate() float64 {
	if x != nil {
		return x.ContextSwitchRate
	}
	return 0
}

func (x *RuntimeProfile) GetSampleCount() int64 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

func (x *RuntimeProfile) GetWindowStartNs() int64 {
	if x != nil {
		return x.WindowStartNs
	}
	return 0
}

func (x *RuntimeProfile) GetWindowEndNs() int64 {
	if x != nil {
		return x.WindowEndNs
	}
	return 0
}

func (x *RuntimeProfile) GetConfidence() ProfileConfidence {
	if x != nil {
		return x.Confidence
	}
	return ProfileConfidence_PROFILE_CONFIDENCE_UNKNOWN
}

type NodeProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeProfilesRequest) Reset() {
	*x = NodeProfilesRequest{}
	mi := &file_pkg_proto_akil_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeProfilesRequest) ProtoMessage() {}

func (x *NodeProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_akil_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeProfilesRequest.ProtoReflect.Descriptor instead.
func (*NodeProfilesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{9}
}

func (x *NodeProfilesRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type NodeProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*RuntimeProfile      `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeProfilesResponse) Reset() {
	*x = NodeProfilesResponse{}
	mi := &file_pkg_proto_akil_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeProfilesResponse) ProtoMessage() {}

func (x *NodeProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_akil_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeProfilesResponse.ProtoReflect.Descriptor instead.
func (*NodeProfilesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_akil_proto_rawDescGZIP(), []int{10}
}

func (x *NodeProfilesResponse) GetProfiles() []*RuntimeProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_pkg_proto_akil_proto protoreflect.FileDescriptor

const file_pkg_proto_akil_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/akil.proto\x12\aakil.v1\"\x8c\x01\n" +
	"\x0eTelemetryBatch\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12,\n" +
	"\x12batch_timestamp_ns\x18\x02 \x01(\x03R\x10batchTimestampNs\x12/\n" +
	"\x06events\x18\x03 \x03(\v2\x17.akil.v1.TelemetryEventR\x06events\"\x8f\x03\n" +
	"\x0eTelemetryEvent\x121\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x12.akil.v1.EventTypeR\teventType\x12!\n" +
	"\fworkload_key\x18\x02 \x01(\tR\vworkloadKey\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\x128\n" +
	"\n" +
	"page_fault\x18\x04 \x01(\v2\x17.akil.v1.PageFaultEventH\x00R\tpageFault\x128\n" +
	"\n" +
	"cache_miss\x18\x05 \x01(\v2\x17.akil.v1.CacheMissEventH\x00R\tcacheMiss\x12G\n" +
	"\x0flock_contention\x18\x06 \x01(\v2\x1c.akil.v1.LockContentionEventH\x00R\x0elockContention\x12<\n" +
	"\n" +
	"ctx_switch\x18\a \x01(\v2\x1b.akil.v1.ContextSwitchEventH\x00R\tctxSwitchB\t\n" +
	"\apayload\"E\n" +
	"\x0ePageFaultEvent\x12\x19\n" +
	"\bis_major\x18\x01 \x01(\bR\aisMajor\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\x04R\aaddress\":\n" +
	"\x0eCacheMissEvent\x12(\n" +
	"\x10miss_count_delta\x18\x01 \x01(\x04R\x0emissCountDelta\"Y\n" +
	"\x13LockContentionEvent\x12!\n" +
	"\flock_address\x18\x01 \x01(\x04R\vlockAddress\x12\x1f\n" +
	"\vduration_ns\x18\x02 \x01(\x03R\n" +
	"durationNs\"_\n" +
	"\x12ContextSwitchEvent\x12*\n" +
	"\x11prev_workload_key\x18\x01 \x01(\tR\x0fprevWorkloadKey\x12\x1d\n" +
	"\n" +
	"prev_state\x18\x02 \x01(\x05R\tprevState\"h\n" +
	"\tIngestAck\x12,\n" +
	"\x12acked_timestamp_ns\x18\x01 \x01(\x03R\x10ackedTimestampNs\x12-\n" +
	"\x12apply_backpressure\x18\x02 \x01(\bR\x11applyBackpressure\"3\n" +
	"\x0eProfileRequest\x12!\n" +
	"\fworkload_key\x18\x01 \x01(\tR\vworkloadKey\"\x92\x03\n" +
	"\x0eRuntimeProfile\x12!\n" +
	"\fworkload_key\x18\x01 \x01(\tR\vworkloadKey\x12&\n" +
	"\x0fpage_fault_rate\x18\x02 \x01(\x01R\rpageFaultRate\x12&\n" +
	"\x0fcache_miss_rate\x18\x03 \x01(\x01R\rcacheMissRate\x122\n" +
	"\x15lock_contention_ratio\x18\x04 \x01(\x01R\x13lockContentionRatio\x12.\n" +
	"\x13context_switch_rate\x18\x05 \x01(\x01R\x11contextSwitchRate\x12!\n" +
	"\fsample_count\x18\x06 \x01(\x03R\vsampleCount\x12&\n" +
	"\x0fwindow_start_ns\x18\a \x01(\x03R\rwindowStartNs\x12\"\n" +
	"\rwindow_end_ns\x18\b \x01(\x03R\vwindowEndNs\x12:\n" +
	"\n" +
	"confidence\x18\t \x01(\x0e2\x1a.akil.v1.ProfileConfidenceR\n" +
	"confidence\"2\n" +
	"\x13NodeProfilesRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\"K\n" +
	"\x14NodeProfilesResponse\x123\n" +
	"\bprofiles\x18\x01 \x03(\v2\x17.akil.v1.RuntimeProfileR\bprofiles*\x9c\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_TYPE_PAGE_FAULT\x10\x01\x12\x19\n" +
	"\x15EVENT_TYPE_CACHE_MISS\x10\x02\x12\x1e\n" +
	"\x1aEVENT_TYPE_LOCK_CONTENTION\x10\x03\x12\x1d\n" +
	"\x19EVENT_TYPE_CONTEXT_SWITCH\x10\x04*\x8b\x01\n" +
	"\x11ProfileConfidence\x12\x1e\n" +
	"\x1aPROFILE_CONFIDENCE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16PROFILE_CONFIDENCE_LOW\x10\x01\x12\x1d\n" +
	"\x19PROFILE_CONFIDENCE_MEDIUM\x10\x02\x12\x1b\n" +
	"\x17PROFILE_CONFIDENCE_HIGH\x10\x032\xe7\x01\n" +
	"\rAkilTelemetry\x12B\n" +
	"\x0fStreamTelemetry\x12\x17.akil.v1.TelemetryBatch\x1a\x12.akil.v1.IngestAck(\x010\x01\x12@\n" +
	"\fQueryProfile\x12\x17.akil.v1.ProfileRequest\x1a\x17.akil.v1.RuntimeProfile\x12P\n" +
	"\x11QueryNodeProfiles\x12\x1c.akil.v1.NodeProfilesRequest\x1a\x1d.akil.v1.NodeProfilesResponseB%Z#github.com/Yuvraj675/akil/pkg/protob\x06proto3"

var (
	file_pkg_proto_akil_proto_rawDescOnce sync.Once
	file_pkg_proto_akil_proto_rawDescData []byte
)

func file_pkg_proto_akil_proto_rawDescGZIP() []byte {
	file_pkg_proto_akil_proto_rawDescOnce.Do(func() {
		file_pkg_proto_akil_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_akil_proto_rawDesc), len(file_pkg_proto_akil_proto_rawDesc)))
	})
	return file_pkg_proto_akil_proto_rawDescData
}

var file_pkg_proto_akil_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_proto_akil_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_proto_akil_proto_goTypes = []any{
	(EventType)(0),               // 0: akil.v1.EventType
	(ProfileConfidence)(0),       // 1: akil.v1.ProfileConfidence
	(*TelemetryBatch)(nil),       // 2: akil.v1.TelemetryBatch
	(*TelemetryEvent)(nil),       // 3: akil.v1.TelemetryEvent
	(*PageFaultEvent)(nil),       // 4: akil.v1.PageFaultEvent
	(*CacheMissEvent)(nil),       // 5: akil.v1.CacheMissEvent
	(*LockContentionEvent)(nil),  // 6: akil.v1.LockContentionEvent
	(*ContextSwitchEvent)(nil),   // 7: akil.v1.ContextSwitchEvent
	(*IngestAck)(nil),            // 8: akil.v1.IngestAck
	(*ProfileRequest)(nil),       // 9: akil.v1.ProfileRequest
	(*RuntimeProfile)(nil),       // 10: akil.v1.RuntimeProfile
	(*NodeProfilesRequest)(nil),  // 11: akil.v1.NodeProfilesRequest
	(*NodeProfilesResponse)(nil), // 12: akil.v1.NodeProfilesResponse
}
var file_pkg_proto_akil_proto_depIdxs = []int32{
	3,  // 0: akil.v1.TelemetryBatch.events:type_name -> akil.v1.TelemetryEvent
	0,  // 1: akil.v1.TelemetryEvent.event_type:type_name -> akil.v1.EventType
	4,  // 2: akil.v1.TelemetryEvent.page_fault:type_name -> akil.v1.PageFaultEvent
	5,  // 3: akil.v1.TelemetryEvent.cache_miss:type_name -> akil.v1.CacheMissEvent
	6,  // 4: akil.v1.TelemetryEvent.lock_contention:type_name -> akil.v1.LockContentionEvent
	7,  // 5: akil.v1.TelemetryEvent.ctx_switch:type_name -> akil.v1.ContextSwitchEvent
	1,  // 6: akil.v1.RuntimeProfile.confidence:type_name -> akil.v1.ProfileConfidence
	10, // 7: akil.v1.NodeProfilesResponse.profiles:type_name -> akil.v1.RuntimeProfile
	2,  // 8: akil.v1.AkilTelemetry.StreamTelemetry:input_type -> akil.v1.TelemetryBatch
	9,  // 9: akil.v1.AkilTelemetry.QueryProfile:input_type -> akil.v1.ProfileRequest
	11, // 10: akil.v1.AkilTelemetry.QueryNodeProfiles:input_type -> akil.v1.NodeProfilesRequest
	8,  // 11: akil.v1.AkilTelemetry.StreamTelemetry:output_type -> akil.v1.IngestAck
	10, // 12: akil.v1.AkilTelemetry.QueryProfile:output_type -> akil.v1.RuntimeProfile
	12, // 13: akil.v1.AkilTelemetry.QueryNodeProfiles:output_type -> akil.v1.NodeProfilesResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_proto_akil_proto_init() }
func file_pkg_proto_akil_proto_init() {
	if File_pkg_proto_akil_proto != nil {
		return
	}
	file_pkg_proto_akil_proto_msgTypes[1].OneofWrappers = []any{
		(*TelemetryEvent_PageFault)(nil),
		(*TelemetryEvent_CacheMiss)(nil),
		(*TelemetryEvent_LockContention)(nil),
		(*TelemetryEvent_CtxSwitch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_akil_proto_rawDesc), len(file_pkg_proto_akil_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_akil_proto_goTypes,
		DependencyIndexes: file_pkg_proto_akil_proto_depIdxs,
		EnumInfos:         file_pkg_proto_akil_proto_enumTypes,
		MessageInfos:      file_pkg_proto_akil_proto_msgTypes,
	}.Build()
	File_pkg_proto_akil_proto = out.File
	file_pkg_proto_akil_proto_goTypes = nil
	file_pkg_proto_akil_proto_depIdxs = nil
}
