// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.5
// source: pkg/proto/akil.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AkilTelemetry_StreamTelemetry_FullMethodName   = "/akil.v1.AkilTelemetry/StreamTelemetry"
	AkilTelemetry_QueryProfile_FullMethodName      = "/akil.v1.AkilTelemetry/QueryProfile"
	AkilTelemetry_QueryNodeProfiles_FullMethodName = "/akil.v1.AkilTelemetry/QueryNodeProfiles"
)

// AkilTelemetryClient is the client API for AkilTelemetry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AkilTelemetry is the core gRPC service for AKIL.
// It provides both ingestion (collector → aggregator) and query (plugin → aggregator) APIs.
type AkilTelemetryClient interface {
	// StreamTelemetry: Collectors stream batches of kernel events.
	// Aggregator responds with acks containing optional backpressure signals.
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryBatch, IngestAck], error)
	// QueryProfile: Scheduler plugin requests a single workload's runtime profile.
	QueryProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*RuntimeProfile, error)
	// QueryNodeProfiles: Scheduler plugin requests all workload profiles on a node.
	QueryNodeProfiles(ctx context.Context, in *NodeProfilesRequest, opts ...grpc.CallOption) (*NodeProfilesResponse, error)
}

type akilTelemetryClient struct {
	cc grpc.ClientConnInterface
}

func NewAkilTelemetryClient(cc grpc.ClientConnInterface) AkilTelemetryClient {
	return &akilTelemetryClient{cc}
}

func (c *akilTelemetryClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryBatch, IngestAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AkilTelemetry_ServiceDesc.Streams[0], AkilTelemetry_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryBatch, IngestAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AkilTelemetry_StreamTelemetryClient = grpc.BidiStreamingClient[TelemetryBatch, IngestAck]

func (c *akilTelemetryClient) QueryProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*RuntimeProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeProfile)
	err := c.cc.Invoke(ctx, AkilTelemetry_QueryProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akilTelemetryClient) QueryNodeProfiles(ctx context.Context, in *NodeProfilesRequest, opts ...grpc.CallOption) (*NodeProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeProfilesResponse)
	err := c.cc.Invoke(ctx, AkilTelemetry_QueryNodeProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AkilTelemetryServer is the server API for AkilTelemetry service.
// All implementations must embed UnimplementedAkilTelemetryServer
// for forward compatibility.
//
// AkilTelemetry is the core gRPC service for AKIL.
// It provides both ingestion (collector → aggregator) and query (plugin → aggregator) APIs.
type AkilTelemetryServer interface {
	// StreamTelemetry: Collectors stream batches of kernel events.
	// Aggregator responds with acks containing optional backpressure signals.
	StreamTelemetry(grpc.BidiStreamingServer[TelemetryBatch, IngestAck]) error
	// QueryProfile: Scheduler plugin requests a single workload's runtime profile.
	QueryProfile(context.Context, *ProfileRequest) (*RuntimeProfile, error)
	// QueryNodeProfiles: Scheduler plugin requests all workload profiles on a node.
	QueryNodeProfiles(context.Context, *NodeProfilesRequest) (*NodeProfilesResponse, error)
	mustEmbedUnimplementedAkilTelemetryServer()
}

// UnimplementedAkilTelemetryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAkilTelemetryServer struct{}

func (UnimplementedAkilTelemetryServer) StreamTelemetry(grpc.BidiStreamingServer[TelemetryBatch, IngestAck]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedAkilTelemetryServer) QueryProfile(context.Context, *ProfileRequest) (*RuntimeProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryProfile not implemented")
}
func (UnimplementedAkilTelemetryServer) QueryNodeProfiles(context.Context, *NodeProfilesRequest) (*NodeProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryNodeProfiles not implemented")
}
func (UnimplementedAkilTelemetryServer) mustEmbedUnimplementedAkilTelemetryServer() {}
func (UnimplementedAkilTelemetryServer) testEmbeddedByValue()                       {}

// UnsafeAkilTelemetryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AkilTelemetryServer will
// result in compilation errors.
type UnsafeAkilTelemetryServer interface {
	mustEmbedUnimplementedAkilTelemetryServer()
}

func RegisterAkilTelemetryServer(s grpc.ServiceRegistrar, srv AkilTelemetryServer) {
	// If the following call panics, it indicates UnimplementedAkilTelemetryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AkilTelemetry_ServiceDesc, srv)
}

func _AkilTelemetry_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AkilTelemetryServer).StreamTelemetry(&grpc.GenericServerStream[TelemetryBatch, IngestAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AkilTelemetry_StreamTelemetryServer = grpc.BidiStreamingServer[TelemetryBatch, IngestAck]

func _AkilTelemetry_QueryProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkilTelemetryServer).QueryProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkilTelemetry_QueryProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkilTelemetryServer).QueryProfile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AkilTelemetry_QueryNodeProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkilTelemetryServer).QueryNodeProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AkilTelemetry_QueryNodeProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkilTelemetryServer).QueryNodeProfiles(ctx, req.(*NodeProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AkilTelemetry_ServiceDesc is the grpc.ServiceDesc for AkilTelemetry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AkilTelemetry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "akil.v1.AkilTelemetry",
	HandlerType: (*AkilTelemetryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryProfile",
			Handler:    _AkilTelemetry_QueryProfile_Handler,
		},
		{
			MethodName: "QueryNodeProfiles",
			Handler:    _AkilTelemetry_QueryNodeProfiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _AkilTelemetry_StreamTelemetry_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/akil.proto",
}
