package ebpf

import (
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"unsafe"

	"github.com/Yuvraj675/akil/pkg/telemetry"
)

// AkilEventSize is the size of the akil_event struct in the BPF ring buffer.
// This must match the C struct layout in akil.c.
const AkilEventSize = 64

// RawBPFEvent is the raw byte representation of the akil_event C struct.
// Fields are laid out to match the C struct with natural alignment.
type RawBPFEvent struct {
	EventType uint8
	_         [7]byte // padding to align cgroup_id
	CgroupID  uint64
	Timestamp uint64
	Payload   [40]byte // union payload — largest variant
}

// Loader manages the lifecycle of AKIL eBPF programs and maps.
type Loader struct {
	logger *slog.Logger
	events chan telemetry.RawEvent
	// In production, these would be cilium/ebpf objects.
	// For Phase 1 compilation, we use a stub interface.
	closers []func() error
}

// LoaderConfig configures the eBPF loader.
type LoaderConfig struct {
	// RingBufferSize is the size of the shared BPF ring buffer in bytes.
	// Default: 16 MB.
	RingBufferSize int

	// CacheMissSamplePeriod is the number of LLC misses between perf event samples.
	// Default: 10000.
	CacheMissSamplePeriod uint64

	// EventChannelSize is the buffer size of the Go channel receiving parsed events.
	// Default: 8192.
	EventChannelSize int

	Logger *slog.Logger
}

// DefaultLoaderConfig returns a LoaderConfig with sensible defaults.
func DefaultLoaderConfig() LoaderConfig {
	return LoaderConfig{
		RingBufferSize:        16 * 1024 * 1024, // 16 MB
		CacheMissSamplePeriod: 10000,
		EventChannelSize:      8192,
		Logger:                slog.Default(),
	}
}

// NewLoader creates a new eBPF Loader with the given configuration.
// It loads and attaches all four eBPF programs and opens the shared ring buffer.
//
// The caller must call Close() when done to detach programs and release resources.
func NewLoader(cfg LoaderConfig) (*Loader, error) {
	if cfg.Logger == nil {
		cfg.Logger = slog.Default()
	}
	if cfg.EventChannelSize == 0 {
		cfg.EventChannelSize = 8192
	}

	l := &Loader{
		logger: cfg.Logger,
		events: make(chan telemetry.RawEvent, cfg.EventChannelSize),
	}

	cfg.Logger.Info("eBPF loader initialized",
		"ring_buffer_size", cfg.RingBufferSize,
		"cache_miss_sample_period", cfg.CacheMissSamplePeriod,
	)

	// NOTE: Actual eBPF loading requires cilium/ebpf objects generated by bpf2go.
	// The full loading sequence is:
	//
	// 1. Load compiled eBPF objects:
	//    objs := akilObjects{}
	//    if err := loadAkilObjects(&objs, nil); err != nil { ... }
	//
	// 2. Attach tracepoints:
	//    link.Tracepoint("exceptions", "page_fault_user", objs.AkilPageFaultUser, nil)
	//    link.Tracepoint("exceptions", "page_fault_kernel", objs.AkilPageFaultKernel, nil)
	//    link.Tracepoint("lock", "contention_begin", objs.AkilLockContentionBegin, nil)
	//    link.Tracepoint("lock", "contention_end", objs.AkilLockContentionEnd, nil)
	//    link.Tracepoint("sched", "sched_switch", objs.AkilSchedSwitch, nil)
	//
	// 3. Attach perf event for cache misses:
	//    perfEvent, _ := perf.NewReader(objs.Events, cfg.RingBufferSize)
	//
	// 4. Open ring buffer reader:
	//    ringbuf.NewReader(objs.Events)
	//
	// This is documented here so the loading can be implemented once bpf2go
	// generation is set up in the build environment.

	return l, nil
}

// Events returns a read-only channel of parsed kernel events.
// The channel is populated by the ring buffer reader goroutine.
func (l *Loader) Events() <-chan telemetry.RawEvent {
	return l.events
}

// Start begins reading events from the BPF ring buffer in a background goroutine.
// It blocks until the context is cancelled.
func (l *Loader) Start(ctx context.Context) error {
	l.logger.Info("starting eBPF ring buffer reader")

	// NOTE: In production, this would use ringbuf.NewReader to read from the
	// BPF ring buffer. The reader calls ringbuf.Read() in a loop, parses the
	// raw bytes into telemetry.RawEvent, and sends them to l.events.
	//
	// Stub implementation waits for context cancellation:
	<-ctx.Done()
	return ctx.Err()
}

// ParseRawEvent converts raw bytes from the BPF ring buffer into a typed RawEvent.
func ParseRawEvent(data []byte) (telemetry.RawEvent, error) {
	if len(data) < int(unsafe.Sizeof(RawBPFEvent{})) {
		return telemetry.RawEvent{}, fmt.Errorf("event too small: %d bytes", len(data))
	}

	raw := RawBPFEvent{}
	raw.EventType = data[0]
	raw.CgroupID = binary.LittleEndian.Uint64(data[8:16])
	raw.Timestamp = binary.LittleEndian.Uint64(data[16:24])

	evt := telemetry.RawEvent{
		Type:        telemetry.EventType(raw.EventType),
		CgroupID:    raw.CgroupID,
		TimestampNs: raw.Timestamp,
	}

	payloadData := data[24:]

	switch evt.Type {
	case telemetry.EventPageFault:
		if len(payloadData) < 9 {
			return evt, fmt.Errorf("page fault payload too small")
		}
		evt.Payload = telemetry.PageFaultPayload{
			IsMajor: payloadData[0] != 0,
			Address: binary.LittleEndian.Uint64(payloadData[1:9]),
		}

	case telemetry.EventCacheMiss:
		if len(payloadData) < 8 {
			return evt, fmt.Errorf("cache miss payload too small")
		}
		evt.Payload = telemetry.CacheMissPayload{
			MissCountDelta: binary.LittleEndian.Uint64(payloadData[0:8]),
		}

	case telemetry.EventLockContention:
		if len(payloadData) < 16 {
			return evt, fmt.Errorf("lock contention payload too small")
		}
		evt.Payload = telemetry.LockContentionPayload{
			LockAddress: binary.LittleEndian.Uint64(payloadData[0:8]),
			DurationNs:  int64(binary.LittleEndian.Uint64(payloadData[8:16])),
		}

	case telemetry.EventCtxSwitch:
		if len(payloadData) < 20 {
			return evt, fmt.Errorf("ctx switch payload too small")
		}
		evt.Payload = telemetry.CtxSwitchPayload{
			PrevCgroupID: binary.LittleEndian.Uint64(payloadData[0:8]),
			NextCgroupID: binary.LittleEndian.Uint64(payloadData[8:16]),
			PrevState:    int32(binary.LittleEndian.Uint32(payloadData[16:20])),
		}

	default:
		return evt, fmt.Errorf("unknown event type: %d", raw.EventType)
	}

	return evt, nil
}

// Close detaches all eBPF programs and releases resources.
func (l *Loader) Close() error {
	l.logger.Info("closing eBPF loader")
	var errs []error
	for _, closer := range l.closers {
		if err := closer(); err != nil {
			errs = append(errs, err)
		}
	}
	close(l.events)
	return errors.Join(errs...)
}

// CheckBPFSupport verifies that the running kernel supports the required BPF features.
func CheckBPFSupport() error {
	// Check for BTF support
	if _, err := os.Stat("/sys/kernel/btf/vmlinux"); err != nil {
		return fmt.Errorf("BTF not available (kernel too old or CONFIG_DEBUG_INFO_BTF not enabled): %w", err)
	}
	return nil
}
